
spring:
  application:
    name: habit-challenge

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

jwt:
  secret: rU5jD7yJf9uB1mYpGxTqN8vFzWc2hR7tKj6pX1aQ4zL9oE3sH5vU7yW8xC9dZ2qB
  expiration: 86400000

logging:
  level:
    com.habitchallenge: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: "Challenge MVP Backend API"
    description: "Spring Boot REST API for habit and goal management SNS platform"
    version: "1.7.0"

server:
  port: ${PORT:8080}