
spring:
  application:
    name: habit-challenge

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

jwt:
  secret: rU5jD7yJf9uB1mYpGxTqN8vFzWc2hR7tKj6pX1aQ4zL9oE3sH5vU7yW8xC9dZ2qB
  expiration: 86400000

logging:
  level:
    com.habitchallenge: DEBUG
server:
  port: 8888